trigger: 
- master

pool: 
   vmImage: ubuntu-latest

jobs:
- deployment: VMDeploy
  displayName: Deploy to VM
  environment: 
   name: keycloack-environment
   resourceType: VirtualMachine
  strategy:
     runOnce:
        deploy:   
          steps:
            - script: echo "Hello world"